import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import './globals.css';
import { Header } from '@/components/shared/Header';
import { Footer } from '@/components/shared/Footer';
import { Hero } from '@/components/home/Hero';
import { Description } from '@/components/home/Description';

export const metadata: Metadata = {
    title: 'Ecommerce',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.svg', // /public path
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${GeistSans.className} flex flex-col text-center w-full h-full`}
            >
                <Header />
                <Hero />
                {children}
                <Footer />
            </body>
        </html>
    );
}
