import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import './globals.css';
import { Header } from '@/components/shared/Header';
import { Footer } from '@/components/shared/Footer';
import { ChatProvider } from '@/components/layout/ChatProvider';

export const metadata: Metadata = {
    title: 'Home: Future',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.svg', // /public path
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={GeistSans.className}>
                <Header />
                {children}
                <ChatProvider />
                <Footer />
            </body>
        </html>
    );
}
